# coding: utf-8

"""
    Motion REST API

    <!-- theme: warning -->  > ### Rate Limit Information > > The Motion API is currently rate limited to 12 requests per minute per user. In the event a user exceeds this rate limit 3 times > in a singe 24 hour period, their API access will be disabled and will require that they contact support to have it re-enabled.  <!-- theme: info -->  > ### Note on Date Formats > > All dates that the Motion API works with are in the format of ISO 8601. **Motion will always return dates in UTC.** 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_projects_controller_get(self) -> None:
        """Test case for projects_controller_get

        List Projects
        """
        pass

    def test_projects_controller_get_single_project(self) -> None:
        """Test case for projects_controller_get_single_project

        Retrieve Project
        """
        pass

    def test_projects_controller_post(self) -> None:
        """Test case for projects_controller_post

        Create Project
        """
        pass


if __name__ == '__main__':
    unittest.main()
