# coding: utf-8

"""
    Motion REST API

    <!-- theme: warning -->  > ### Rate Limit Information > > The Motion API is currently rate limited to 12 requests per minute per user. In the event a user exceeds this rate limit 3 times > in a singe 24 hour period, their API access will be disabled and will require that they contact support to have it re-enabled.  <!-- theme: info -->  > ### Note on Date Formats > > All dates that the Motion API works with are in the format of ISO 8601. **Motion will always return dates in UTC.** 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TasksApi()

    def tearDown(self) -> None:
        pass

    def test_tasks_controller_delete_assignee(self) -> None:
        """Test case for tasks_controller_delete_assignee

        Unassign a task
        """
        pass

    def test_tasks_controller_delete_task(self) -> None:
        """Test case for tasks_controller_delete_task

        Delete a Task
        """
        pass

    def test_tasks_controller_get(self) -> None:
        """Test case for tasks_controller_get

        List Tasks
        """
        pass

    def test_tasks_controller_get_by_id(self) -> None:
        """Test case for tasks_controller_get_by_id

        Retrieve a Task
        """
        pass

    def test_tasks_controller_move_task(self) -> None:
        """Test case for tasks_controller_move_task

        Move Workspace
        """
        pass

    def test_tasks_controller_post(self) -> None:
        """Test case for tasks_controller_post

        Create Task
        """
        pass

    def test_tasks_controller_update_task(self) -> None:
        """Test case for tasks_controller_update_task

        Update a Task
        """
        pass


if __name__ == '__main__':
    unittest.main()
