# coding: utf-8

"""
    Motion REST API

    <!-- theme: warning -->  > ### Rate Limit Information > > The Motion API is currently rate limited to 12 requests per minute per user. In the event a user exceeds this rate limit 3 times > in a singe 24 hour period, their API access will be disabled and will require that they contact support to have it re-enabled.  <!-- theme: info -->  > ### Note on Date Formats > > All dates that the Motion API works with are in the format of ISO 8601. **Motion will always return dates in UTC.** 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.recurring_tasks_post import RecurringTasksPost

class TestRecurringTasksPost(unittest.TestCase):
    """RecurringTasksPost unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RecurringTasksPost:
        """Test RecurringTasksPost
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RecurringTasksPost`
        """
        model = RecurringTasksPost()
        if include_optional:
            return RecurringTasksPost(
                frequency = '',
                deadline_type = 'SOFT',
                duration = None,
                starting_on = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                ideal_time = '',
                schedule = 'Work Hours',
                name = '0',
                workspace_id = '',
                description = '',
                priority = 'MEDIUM',
                assignee_id = ''
            )
        else:
            return RecurringTasksPost(
                frequency = '',
                name = '0',
                workspace_id = '',
                priority = 'MEDIUM',
                assignee_id = '',
        )
        """

    def testRecurringTasksPost(self):
        """Test RecurringTasksPost"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
