# coding: utf-8

"""
    Motion REST API

    <!-- theme: warning -->  > ### Rate Limit Information > > The Motion API is currently rate limited to 12 requests per minute per user. In the event a user exceeds this rate limit 3 times > in a singe 24 hour period, their API access will be disabled and will require that they contact support to have it re-enabled.  <!-- theme: info -->  > ### Note on Date Formats > > All dates that the Motion API works with are in the format of ISO 8601. **Motion will always return dates in UTC.** 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.recurring_tasks_api import RecurringTasksApi


class TestRecurringTasksApi(unittest.TestCase):
    """RecurringTasksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecurringTasksApi()

    def tearDown(self) -> None:
        pass

    def test_recurring_tasks_controller_delete_task(self) -> None:
        """Test case for recurring_tasks_controller_delete_task

        Delete a Recurring Task
        """
        pass

    def test_recurring_tasks_controller_list_recurring_tasks(self) -> None:
        """Test case for recurring_tasks_controller_list_recurring_tasks

        List Recurring Tasks
        """
        pass

    def test_recurring_tasks_controller_post_recurring_task(self) -> None:
        """Test case for recurring_tasks_controller_post_recurring_task

        Create a Recurring Task
        """
        pass


if __name__ == '__main__':
    unittest.main()
