# coding: utf-8

"""
    Motion REST API

    <!-- theme: warning -->  > ### Rate Limit Information > > The Motion API is currently rate limited to 12 requests per minute per user. In the event a user exceeds this rate limit 3 times > in a singe 24 hour period, their API access will be disabled and will require that they contact support to have it re-enabled.  <!-- theme: info -->  > ### Note on Date Formats > > All dates that the Motion API works with are in the format of ISO 8601. **Motion will always return dates in UTC.** 

    The version of the OpenAPI document: 1.0.0
    Contact: christopher.queen@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr, validator


class ProjectPost(BaseModel):
    """
    ProjectPost
    """
    due_date: Optional[datetime] = Field(
        None, alias="dueDate", description="ISO 8601 Due date on the task")
    name: constr(strict=True, min_length=1) = Field(...)
    workspace_id: StrictStr = Field(..., alias="workspaceId")
    description: Optional[StrictStr] = None
    labels: Optional[conlist(StrictStr)] = None
    status: Optional[StrictStr] = None
    priority: Optional[StrictStr] = None
    __properties = [
        "dueDate", "name", "workspaceId", "description", "labels", "status",
        "priority"
    ]

    @validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('ASAP', 'HIGH', 'MEDIUM', 'LOW'):
            raise ValueError(
                "must be one of enum values ('ASAP', 'HIGH', 'MEDIUM', 'LOW')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProjectPost:
        """Create an instance of ProjectPost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProjectPost:
        """Create an instance of ProjectPost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProjectPost.parse_obj(obj)

        _obj = ProjectPost.parse_obj({
            "due_date": obj.get("dueDate"),
            "name": obj.get("name"),
            "workspace_id": obj.get("workspaceId"),
            "description": obj.get("description"),
            "labels": obj.get("labels"),
            "status": obj.get("status"),
            "priority": obj.get("priority")
        })
        return _obj
