# coding: utf-8

"""
    Motion REST API

    <!-- theme: warning -->  > ### Rate Limit Information > > The Motion API is currently rate limited to 12 requests per minute per user. In the event a user exceeds this rate limit 3 times > in a singe 24 hour period, their API access will be disabled and will require that they contact support to have it re-enabled.  <!-- theme: info -->  > ### Note on Date Formats > > All dates that the Motion API works with are in the format of ISO 8601. **Motion will always return dates in UTC.** 

    The version of the OpenAPI document: 1.0.0
    Contact: christopher.queen@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist, constr, validator
from usemotion_api_client.models.auto_scheduled_info import AutoScheduledInfo
from usemotion_api_client.models.task_duration import TaskDuration


class TaskPost(BaseModel):
    """
    TaskPost
    """
    due_date: Optional[datetime] = Field(
        None,
        alias="dueDate",
        description=
        "ISO 8601 Due date on the task. REQUIRED for scheduled tasks")
    duration: Optional[TaskDuration] = None
    status: Optional[StrictStr] = Field(
        None, description="Defaults to workspace default status.")
    auto_scheduled: Optional[AutoScheduledInfo] = Field(None,
                                                        alias="autoScheduled")
    name: constr(strict=True,
                 min_length=1) = Field(...,
                                       description="Name / title of the task")
    project_id: Optional[StrictStr] = Field(None, alias="projectId")
    workspace_id: StrictStr = Field(..., alias="workspaceId")
    description: Optional[StrictStr] = Field(
        None, description="Input as GitHub Flavored Markdown")
    priority: Optional[StrictStr] = 'MEDIUM'
    labels: Optional[conlist(StrictStr)] = None
    assignee_id: Optional[StrictStr] = Field(
        None,
        alias="assigneeId",
        description="The user id the task should be assigned to")
    __properties = [
        "dueDate", "duration", "status", "autoScheduled", "name", "projectId",
        "workspaceId", "description", "priority", "labels", "assigneeId"
    ]

    @validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('ASAP', 'HIGH', 'MEDIUM', 'LOW'):
            raise ValueError(
                "must be one of enum values ('ASAP', 'HIGH', 'MEDIUM', 'LOW')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TaskPost:
        """Create an instance of TaskPost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of duration
        if self.duration:
            _dict['duration'] = self.duration.to_dict()
        # override the default output from pydantic by calling `to_dict()` of auto_scheduled
        if self.auto_scheduled:
            _dict['autoScheduled'] = self.auto_scheduled.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TaskPost:
        """Create an instance of TaskPost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TaskPost.parse_obj(obj)

        _obj = TaskPost.parse_obj({
            "due_date":
            obj.get("dueDate"),
            "duration":
            TaskDuration.from_dict(obj.get("duration"))
            if obj.get("duration") is not None else None,
            "status":
            obj.get("status"),
            "auto_scheduled":
            AutoScheduledInfo.from_dict(obj.get("autoScheduled"))
            if obj.get("autoScheduled") is not None else None,
            "name":
            obj.get("name"),
            "project_id":
            obj.get("projectId"),
            "workspace_id":
            obj.get("workspaceId"),
            "description":
            obj.get("description"),
            "priority":
            obj.get("priority")
            if obj.get("priority") is not None else 'MEDIUM',
            "labels":
            obj.get("labels"),
            "assignee_id":
            obj.get("assigneeId")
        })
        return _obj
