# coding: utf-8

"""
    Motion REST API

    <!-- theme: warning -->  > ### Rate Limit Information > > The Motion API is currently rate limited to 12 requests per minute per user. In the event a user exceeds this rate limit 3 times > in a singe 24 hour period, their API access will be disabled and will require that they contact support to have it re-enabled.  <!-- theme: info -->  > ### Note on Date Formats > > All dates that the Motion API works with are in the format of ISO 8601. **Motion will always return dates in UTC.** 

    The version of the OpenAPI document: 1.0.0
    Contact: christopher.queen@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist, validator
from usemotion_api_client.models.label import Label
from usemotion_api_client.models.project import Project
from usemotion_api_client.models.status import Status
from usemotion_api_client.models.task_duration import TaskDuration
from usemotion_api_client.models.user import User
from usemotion_api_client.models.workspace import Workspace


class Task(BaseModel):
    """
    Task
    """
    duration: Optional[TaskDuration] = None
    workspace: Workspace = Field(...)
    id: StrictStr = Field(...)
    name: StrictStr = Field(...)
    description: Optional[StrictStr] = None
    due_date: datetime = Field(..., alias="dueDate")
    deadline_type: StrictStr = Field(..., alias="deadlineType")
    parent_recurring_task_id: StrictStr = Field(...,
                                                alias="parentRecurringTaskId")
    completed: StrictBool = Field(...)
    creator: User = Field(...)
    project: Optional[Project] = None
    status: Status = Field(...)
    priority: StrictStr = Field(...)
    labels: conlist(Label) = Field(...)
    assignees: conlist(User) = Field(...)
    scheduled_start: Optional[datetime] = Field(
        None,
        alias="scheduledStart",
        description="The time that motion has scheduled this task to start")
    created_time: datetime = Field(
        ...,
        alias="createdTime",
        description="The time that the task was created")
    scheduled_end: Optional[datetime] = Field(
        None,
        alias="scheduledEnd",
        description="The time that motion has scheduled this task to end")
    scheduling_issue: StrictBool = Field(
        ...,
        alias="schedulingIssue",
        description=
        "Returns true if Motion was unable to schedule this task. Check Motion directly to address"
    )
    __properties = [
        "duration", "workspace", "id", "name", "description", "dueDate",
        "deadlineType", "parentRecurringTaskId", "completed", "creator",
        "project", "status", "priority", "labels", "assignees",
        "scheduledStart", "createdTime", "scheduledEnd", "schedulingIssue"
    ]

    @validator('deadline_type')
    def deadline_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('HARD', 'SOFT', 'NONE'):
            raise ValueError(
                "must be one of enum values ('HARD', 'SOFT', 'NONE')")
        return value

    @validator('priority')
    def priority_validate_enum(cls, value):
        """Validates the enum"""
        if value not in ('ASAP', 'HIGH', 'MEDIUM', 'LOW'):
            raise ValueError(
                "must be one of enum values ('ASAP', 'HIGH', 'MEDIUM', 'LOW')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Task:
        """Create an instance of Task from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of duration
        if self.duration:
            _dict['duration'] = self.duration.to_dict()
        # override the default output from pydantic by calling `to_dict()` of workspace
        if self.workspace:
            _dict['workspace'] = self.workspace.to_dict()
        # override the default output from pydantic by calling `to_dict()` of creator
        if self.creator:
            _dict['creator'] = self.creator.to_dict()
        # override the default output from pydantic by calling `to_dict()` of project
        if self.project:
            _dict['project'] = self.project.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item in self.labels:
                if _item:
                    _items.append(_item.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in assignees (list)
        _items = []
        if self.assignees:
            for _item in self.assignees:
                if _item:
                    _items.append(_item.to_dict())
            _dict['assignees'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Task:
        """Create an instance of Task from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Task.parse_obj(obj)

        _obj = Task.parse_obj({
            "duration":
            TaskDuration.from_dict(obj.get("duration"))
            if obj.get("duration") is not None else None,
            "workspace":
            Workspace.from_dict(obj.get("workspace"))
            if obj.get("workspace") is not None else None,
            "id":
            obj.get("id"),
            "name":
            obj.get("name"),
            "description":
            obj.get("description"),
            "due_date":
            obj.get("dueDate"),
            "deadline_type":
            obj.get("deadlineType")
            if obj.get("deadlineType") is not None else 'SOFT',
            "parent_recurring_task_id":
            obj.get("parentRecurringTaskId"),
            "completed":
            obj.get("completed"),
            "creator":
            User.from_dict(obj.get("creator"))
            if obj.get("creator") is not None else None,
            "project":
            Project.from_dict(obj.get("project"))
            if obj.get("project") is not None else None,
            "status":
            Status.from_dict(obj.get("status"))
            if obj.get("status") is not None else None,
            "priority":
            obj.get("priority"),
            "labels": [Label.from_dict(_item) for _item in obj.get("labels")]
            if obj.get("labels") is not None else None,
            "assignees":
            [User.from_dict(_item) for _item in obj.get("assignees")]
            if obj.get("assignees") is not None else None,
            "scheduled_start":
            obj.get("scheduledStart"),
            "created_time":
            obj.get("createdTime"),
            "scheduled_end":
            obj.get("scheduledEnd"),
            "scheduling_issue":
            obj.get("schedulingIssue")
        })
        return _obj
