# coding: utf-8

"""
    Motion REST API

    <!-- theme: warning -->  > ### Rate Limit Information > > The Motion API is currently rate limited to 12 requests per minute per user. In the event a user exceeds this rate limit 3 times > in a singe 24 hour period, their API access will be disabled and will require that they contact support to have it re-enabled.  <!-- theme: info -->  > ### Note on Date Formats > > All dates that the Motion API works with are in the format of ISO 8601. **Motion will always return dates in UTC.** 

    The version of the OpenAPI document: 1.0.0
    Contact: christopher.queen@gmail.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from usemotion_api_client.models.label import Label
from usemotion_api_client.models.status import Status


class Workspace(BaseModel):
    """
    Workspace
    """
    id: StrictStr = Field(...)
    name: StrictStr = Field(...)
    team_id: Optional[StrictStr] = Field(None, alias="teamId")
    statuses: conlist(Status) = Field(...)
    labels: conlist(Label) = Field(...)
    type: StrictStr = Field(...)
    __properties = ["id", "name", "teamId", "statuses", "labels", "type"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Workspace:
        """Create an instance of Workspace from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in statuses (list)
        _items = []
        if self.statuses:
            for _item in self.statuses:
                if _item:
                    _items.append(_item.to_dict())
            _dict['statuses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item in self.labels:
                if _item:
                    _items.append(_item.to_dict())
            _dict['labels'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Workspace:
        """Create an instance of Workspace from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Workspace.parse_obj(obj)

        _obj = Workspace.parse_obj({
            "id":
            obj.get("id"),
            "name":
            obj.get("name"),
            "team_id":
            obj.get("teamId"),
            "statuses":
            [Status.from_dict(_item) for _item in obj.get("statuses")]
            if obj.get("statuses") is not None else None,
            "labels": [Label.from_dict(_item) for _item in obj.get("labels")]
            if obj.get("labels") is not None else None,
            "type":
            obj.get("type")
        })
        return _obj
